project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/VictorOmondi1997
      - icon: twitter
        href: https://twitter.com/VictorOmondi197
format:
  html:
    theme: cosmo
    css: styles.css



